name: Deploy Lambda Function

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --only=production

      - name: Create deployment package
        run: |
          # Create a clean deployment directory
          mkdir -p deployment

          # Copy source files
          cp -r src/ deployment/
          cp -r node_modules/ deployment/
          cp package.json deployment/
          cp index.js deployment/

          # Create zip file
          cd deployment
          zip -r ../lambda-deployment.zip .
          cd ..

      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:491641364429:function:lambda-template \
            --zip-file fileb://lambda-deployment.zip

      - name: Cleanup
        run: rm -f lambda-deployment.zip
